using System.Text;
using Firelink.Core.Models.Mo2;

namespace Firelink.Platform.MO2.Writers;

public static class LoadorderWriter
{
    private const string Header =
        "# This file was automatically generated by Mod Organizer.";

    public static void WriteFile(string path, LoadorderFile file)
    {
        var sb = new StringBuilder();
        sb.Append(Header).Append("\r\n");
        foreach (var plugin in file.Plugins)
        {
            sb.Append(plugin).Append("\r\n");
        }

        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }
}
