using System.Text;
using Firelink.Core.Models.Mo2;

namespace Firelink.Platform.MO2.Writers;

/// <summary>
/// Запись modlist.txt.
/// MO2 пишет файл в UTF-8 с BOM, переводы строк CRLF.
/// Порядок строк — как в IEnumerable (не переворачиваем).
/// </summary>
public static class ModlistWriter
{
    private const string Header =
        "# This file was automatically generated by Mod Organizer.";

    public static void WriteFile(string path, ModlistFile file)
    {
        var sb = new StringBuilder();
        sb.Append(Header).Append("\r\n");
        foreach (var entry in file.Entries)
        {
            sb.Append(entry.Enabled ? '+' : '-');
            sb.Append(entry.Name);
            sb.Append("\r\n");
        }

        // UTF-8 with BOM — так делает MO2
        File.WriteAllText(path, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }
}
