<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Firelink.Gui.Verify\Firelink.Gui.Verify.csproj" />
    <ProjectReference Include="..\..\src\Firelink.Gui.Shared\Firelink.Gui.Shared.csproj" />
    <ProjectReference Include="..\..\src\Firelink.Install\Firelink.Install.csproj" />
  </ItemGroup>

</Project>